loki:
  enabled: true
  persistence:
    enabled: false

promtail:
  enabled: true
  hostNetwork: false
  dnsPolicy: ClusterFirst
  config:
    clients:
      - url: http://loki-headless.monitoring.svc.cluster.local:3100/loki/api/v1/push
        batchsize: 65536
        batchwait: 2s
        timeout: 60s
        backoff_config:
          min_period: 1s
          max_period: 30s
          max_retries: 20

grafana:
  enabled: false
