apiVersion: v1
kind: Service
metadata:
  name: calc-backend
  namespace: calc
spec:
  selector:
    app: calc-backend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
