apiVersion: v1
kind: Service
metadata:
  name: calc-frontend
  namespace: calc
spec:
  selector:
    app: calc-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
