apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calc-ingress
  namespace: calc
spec:
  ingressClassName: nginx
  rules:
    - host: ivank.duckdns.org
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: calc-backend
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calc-frontend
                port:
                  number: 80
